### ISSUE TITLE
Post-PR 53/69/89

### ISSUE THREAD

**Issue by jakub-g** [attester/attester#92]
- [ ] attester/attester-doc#1
- [ ] attester/attester-contrib-requirejs#1
- [ ] attester/attester-contrib-noder#2
